version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mental_health_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mental_health_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mental_health_network

  # Backend Node.js API
  backend:
    build: ./backend
    container_name: mental_health_backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/mental_health_db?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 5000
      ML_SERVICE_URL: http://ml-service:5001
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - ml-service
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - mental_health_network

  # ML Service (Flask)
  ml-service:
    build: ./ml-service
    container_name: mental_health_ml
    restart: unless-stopped
    environment:
      PORT: 5001
      FLASK_ENV: production
    ports:
      - "5001:5001"
    networks:
      - mental_health_network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mental_health_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_ML_SERVICE_URL: http://localhost:5001
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mental_health_network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: mental_health_nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - mental_health_network

volumes:
  mongodb_data:
    driver: local

networks:
  mental_health_network:
    driver: bridge